apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      secretKeyRef:
        name: "StateStore:Password"
        key: "StateStore:Password"
    - name: actorStateStore
      value: "true"
auth:
  secretStore: secretstore
