name: Preview - CI
on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'docs/**/*'
    branches: [ main ]
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build, Test, Publish
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build Version
      run: |
        dotnet tool install --global minver-cli --version 4.3.0
        version=$(minver -t v -v e -d preview)
        echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "VERSION=$version"
    - name: Login to container registry
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CLIENTID }}
        password: ${{ secrets.AZURE_CLIENTSECRET }}
    - name: Build Hexalith.AI.AzureBot Container
      run: |
        dotnet publish src/Servers/Hexalith.AI.AzureBot/Hexalith.AI.AzureBot.csproj --configuration Debug -p:Version=${{ env.VERSION }} --os linux --arch x64 /t:PublishContainer
    - name: 'Deploy Hexalith.AI.AzureBot to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/hexalith-ai-azure-bot:${{ env.VERSION }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.AZURE_CLIENTID }}
        registry-password: ${{ secrets.AZURE_CLIENTSECRET }}
        name: hexalith-ai-azure-bot
